version: "3.9"

services:
  api:
    container_name: credit-risk-api
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app              # Mount your local project
      - ./mlruns:/app/mlruns  # Explicitly mount the MLflow tracking folder
    environment:
      - MLFLOW_TRACKING_URI=file:/app/mlruns  # Use local file-based tracking URI
    command: uvicorn src.api.main:app --host 0.0.0.0 --port 8000 --reload
